/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as SuperRouteImport } from './routes/super'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as SuperUsersRouteImport } from './routes/super.users'
import { Route as SuperProcessorRouteImport } from './routes/super.processor'
import { Route as SuperExportsRouteImport } from './routes/super.exports'
import { Route as SuperDlqRouteImport } from './routes/super.dlq'
import { Route as ClientTeamRouteImport } from './routes/client.team'
import { Route as ClientSettingsRouteImport } from './routes/client.settings'
import { Route as ClientIntegrationRouteImport } from './routes/client.integration'

const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const SuperUsersRoute = SuperUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperRoute,
} as any)
const SuperProcessorRoute = SuperProcessorRouteImport.update({
  id: '/processor',
  path: '/processor',
  getParentRoute: () => SuperRoute,
} as any)
const SuperExportsRoute = SuperExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => SuperRoute,
} as any)
const SuperDlqRoute = SuperDlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => SuperRoute,
} as any)
const ClientTeamRoute = ClientTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientIntegrationRoute = ClientIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/developer': typeof DeveloperRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super': typeof SuperRouteWithChildren
  '/viewer': typeof ViewerRoute
  '/client/integration': typeof ClientIntegrationRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/team': typeof ClientTeamRoute
  '/super/dlq': typeof SuperDlqRoute
  '/super/exports': typeof SuperExportsRoute
  '/super/processor': typeof SuperProcessorRoute
  '/super/users': typeof SuperUsersRoute
  '/client/': typeof ClientIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developer': typeof DeveloperRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/viewer': typeof ViewerRoute
  '/client/integration': typeof ClientIntegrationRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/team': typeof ClientTeamRoute
  '/super/dlq': typeof SuperDlqRoute
  '/super/exports': typeof SuperExportsRoute
  '/super/processor': typeof SuperProcessorRoute
  '/super/users': typeof SuperUsersRoute
  '/client': typeof ClientIndexRoute
  '/super': typeof SuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/developer': typeof DeveloperRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super': typeof SuperRouteWithChildren
  '/viewer': typeof ViewerRoute
  '/client/integration': typeof ClientIntegrationRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/team': typeof ClientTeamRoute
  '/super/dlq': typeof SuperDlqRoute
  '/super/exports': typeof SuperExportsRoute
  '/super/processor': typeof SuperProcessorRoute
  '/super/users': typeof SuperUsersRoute
  '/client/': typeof ClientIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/developer'
    | '/login'
    | '/setup'
    | '/sitemap.xml'
    | '/super'
    | '/viewer'
    | '/client/integration'
    | '/client/settings'
    | '/client/team'
    | '/super/dlq'
    | '/super/exports'
    | '/super/processor'
    | '/super/users'
    | '/client/'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developer'
    | '/login'
    | '/setup'
    | '/sitemap.xml'
    | '/viewer'
    | '/client/integration'
    | '/client/settings'
    | '/client/team'
    | '/super/dlq'
    | '/super/exports'
    | '/super/processor'
    | '/super/users'
    | '/client'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/developer'
    | '/login'
    | '/setup'
    | '/sitemap.xml'
    | '/super'
    | '/viewer'
    | '/client/integration'
    | '/client/settings'
    | '/client/team'
    | '/super/dlq'
    | '/super/exports'
    | '/super/processor'
    | '/super/users'
    | '/client/'
    | '/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  DeveloperRoute: typeof DeveloperRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperRoute: typeof SuperRouteWithChildren
  ViewerRoute: typeof ViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/super/users': {
      id: '/super/users'
      path: '/users'
      fullPath: '/super/users'
      preLoaderRoute: typeof SuperUsersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/processor': {
      id: '/super/processor'
      path: '/processor'
      fullPath: '/super/processor'
      preLoaderRoute: typeof SuperProcessorRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/exports': {
      id: '/super/exports'
      path: '/exports'
      fullPath: '/super/exports'
      preLoaderRoute: typeof SuperExportsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/dlq': {
      id: '/super/dlq'
      path: '/dlq'
      fullPath: '/super/dlq'
      preLoaderRoute: typeof SuperDlqRouteImport
      parentRoute: typeof SuperRoute
    }
    '/client/team': {
      id: '/client/team'
      path: '/team'
      fullPath: '/client/team'
      preLoaderRoute: typeof ClientTeamRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/integration': {
      id: '/client/integration'
      path: '/integration'
      fullPath: '/client/integration'
      preLoaderRoute: typeof ClientIntegrationRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientIntegrationRoute: typeof ClientIntegrationRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientTeamRoute: typeof ClientTeamRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientIntegrationRoute: ClientIntegrationRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientTeamRoute: ClientTeamRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface SuperRouteChildren {
  SuperDlqRoute: typeof SuperDlqRoute
  SuperExportsRoute: typeof SuperExportsRoute
  SuperProcessorRoute: typeof SuperProcessorRoute
  SuperUsersRoute: typeof SuperUsersRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperDlqRoute: SuperDlqRoute,
  SuperExportsRoute: SuperExportsRoute,
  SuperProcessorRoute: SuperProcessorRoute,
  SuperUsersRoute: SuperUsersRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  DeveloperRoute: DeveloperRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperRoute: SuperRouteWithChildren,
  ViewerRoute: ViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
